// Flex Message builders — CashGuard "3b" design system (final, by Claude Design).
// Red solid header (#DA1B27), white pill (logo + Carcamstore) top-left, big system
// font title, Cammo mascot on the right, white body. Typed builders — swap the
// visual freely, but keep the postback `action=` strings (the webhook reads them).
//
// Assets are hosted under ASSET_BASE (headers baked to /headers/*.png).
const AB = process.env.ASSET_BASE || '';

// palette
const RED = '#DA1B27', INK = '#17171a', GRAY = '#8a8a93', MUTE = '#a6a6ad',
      VAL = '#26262b', GREEN = '#149a5c', HAIR = '#efeff1', PANEL = '#f6f7f9';

// money: 2 decimals + thousands sep. signMoney prefixes −/+ and colours.
const money = (n: number) => Number(n).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const baht = (n: number) => money(n) + ' ฿';

// ---- header ----
// The header (red banner + Cammo + pill + eyebrow + title) is a pre-rendered hero
// image, baked pixel-for-pixel from the 3b mockup (public/cashguard/headers/*.png,
// generated by gen-headers.mjs). This is the only way to match the mockup's Cammo
// bleed exactly — LINE Flex can't position a floating image like that. Requires
// ASSET_BASE (an unhosted image URL makes LINE reject the card), so hero is omitted
// when it's unset (the card still renders body-only).
const LOGO = `${AB}/cammo/logo-carcam-red.png`;
// name -> Cammo pose (background image) + eyebrow + title (real Flex text overlay)
const HEADER_SPEC: Record<string, { pose: string; eyebrow: string; title: string }> = {
  'ask-evidence':    { pose:'welcome',   eyebrow:'รายจ่าย',      title:'ขอหลักฐาน' },
  'success-expense': { pose:'thumbsup',  eyebrow:'รายจ่าย',      title:'บันทึกสำเร็จ' },
  'ask-slip':        { pose:'welcome',   eyebrow:'เติมเงิน',      title:'ขอสลิปโอนเงิน' },
  'success-topup':   { pose:'growth',    eyebrow:'รายรับ',        title:'เติมเงินสำเร็จ' },
  'group-expense':   { pose:'checklist', eyebrow:'แจ้งเข้ากลุ่ม', title:'ค่าใช้จ่ายใหม่' },
  'group-topup':     { pose:'growth',    eyebrow:'แจ้งเข้ากลุ่ม', title:'เติมเงินใหม่' },
  'group-edit':      { pose:'growth',    eyebrow:'แจ้งเข้ากลุ่ม', title:'มีการแก้ไข' },
  'parse-fail':      { pose:'warn',      eyebrow:'ระบบ',          title:'อ่านรายการไม่ได้' },
  'balance':         { pose:'checklist', eyebrow:'กระเป๋าเงิน',   title:'ยอดคงเหลือ' },
  'expired':         { pose:'wait',      eyebrow:'ระบบ',          title:'รายการหมดอายุ' },
  'duplicate':       { pose:'inspect',   eyebrow:'ความปลอดภัย',   title:'ตรวจพบรูปซ้ำ' },
  'suspicious':      { pose:'inspect',   eyebrow:'ความปลอดภัย',   title:'พบสลิปน่าสงสัย' },
};

// Header = red+Cammo background IMAGE (baked, bleeds like the mockup) with the pill,
// eyebrow and title as REAL Flex text overlaid on top (crisp, correct sizes).
function headerBox(name: string) {
  const s = HEADER_SPEC[name] || HEADER_SPEC['ask-evidence'];
  const bg = { type:'image', url:`${AB}/headers/bg-${s.pose}.png`, size:'full', aspectRatio:'360:132', aspectMode:'cover' };
  const pill = { type:'box', layout:'horizontal', contents:[
    { type:'box', layout:'horizontal', flex:0, backgroundColor:'#FFFFFF', cornerRadius:'16px',
      paddingTop:'3px', paddingBottom:'3px', paddingStart:'6px', paddingEnd:'9px', spacing:'4px', alignItems:'center',
      contents:[
        { type:'image', url:LOGO, size:'14px', aspectMode:'fit', flex:0 },
        { type:'text', text:'Carcamstore', color:RED, weight:'bold', size:'xxs', gravity:'center', flex:0 },
      ]},
    { type:'filler' },
  ]};
  const overlay = { type:'box', layout:'vertical', position:'absolute',
    offsetTop:'0px', offsetStart:'0px', offsetEnd:'0px', offsetBottom:'0px',
    paddingTop:'12px', paddingBottom:'12px', paddingStart:'18px', paddingEnd:'18px',
    contents:[
      pill,
      { type:'filler' }, // pushes the eyebrow+title group to the bottom edge (reliable on LINE)
      { type:'box', layout:'vertical', spacing:'none', contents:[
        { type:'text', text:s.eyebrow, color:'#FFFFFFCC', size:'xs', weight:'bold', offsetTop:'7px' },
        { type:'text', text:s.title, color:'#FFFFFF', weight:'bold', size:'xxl', wrap:false },
      ]},
    ]};
  return { type:'box', layout:'vertical', paddingAll:'0px', contents:[ bg, overlay ] };
}

// ---- body primitives ----
const SEP = { type:'separator', margin:'16px', color:HAIR };
const captionRow = (t: string) => ({ type:'text', text:t, size:'xs', color:MUTE, weight:'bold', wrap:true });
// big amount, sign-coloured + two-tone (big integer, smaller decimal + ฿).
// kind: 'out' (−red) | 'in' (+green) | 'neutral' (ink, gray decimal)
function amount(value: number, kind: 'out' | 'in' | 'neutral') {
  const sign = kind === 'out' ? '−' : kind === 'in' ? '+' : '';
  const color = kind === 'out' ? RED : kind === 'in' ? GREEN : INK;
  const s = money(value); const dot = s.indexOf('.');
  const intPart = dot < 0 ? s : s.slice(0, dot);
  const dec = dot < 0 ? '' : s.slice(dot); // ".00"
  return { type:'text', margin:'xs', weight:'bold', wrap:false, contents:[
    { type:'span', text:`${sign}${intPart}`, size:'4xl', color, weight:'bold' },
    { type:'span', text:`${dec} ฿`, size:'lg', color: kind === 'neutral' ? GRAY : color, weight:'bold' },
  ]};
}
function kv(label: string, value: string, strong = true) {
  return { type:'box', layout:'horizontal', margin:'md', contents:[
    { type:'text', text:label, size:'sm', color:GRAY, flex:0, gravity:'center' },
    { type:'text', text:value, size:'sm', color:strong?VAL:GRAY, weight:strong?'bold':'regular', align:'end', gravity:'center', wrap:true },
  ]};
}
function balanceRow(label: string, value: string | number, color = INK) {
  return { type:'box', layout:'horizontal', margin:'lg', alignItems:'center',
    contents:[
      { type:'text', text:label, size:'sm', color:GRAY, flex:1, gravity:'center' },
      { type:'text', text:baht(Number(value)), size:'xl', weight:'bold', color, align:'end', gravity:'center' },
    ]};
}
// evidence chip — green w/ receipt icon (card 2) or amber w/ dot (card 3), per design
function evidenceChip(has: boolean) {
  if (has) return { type:'box', layout:'horizontal', margin:'14px', backgroundColor:PANEL, cornerRadius:'11px',
    paddingTop:'9px', paddingBottom:'9px', paddingStart:'11px', paddingEnd:'11px', alignItems:'center', spacing:'md', contents:[
      // rounded tile with a small receipt outline inside (design's evidence icon)
      { type:'box', layout:'vertical', width:'34px', height:'34px', backgroundColor:'#e7ebf1', cornerRadius:'8px',
        justifyContent:'center', alignItems:'center', flex:0, contents:[
          { type:'box', layout:'vertical', width:'15px', height:'11px', borderColor:'#9aa3b0', borderWidth:'2px', cornerRadius:'2px', contents:[ { type:'filler' } ] },
        ]},
      { type:'text', text:'แนบใบเสร็จแล้ว', size:'sm', color:'#5c5c66', weight:'bold', flex:1, gravity:'center' },
      { type:'text', text:'มีหลักฐาน', size:'xs', color:GREEN, weight:'bold', align:'end', gravity:'center', flex:0 },
    ]};
  return { type:'box', layout:'horizontal', margin:'14px', backgroundColor:'#fff8ec', borderColor:'#f4e2bd', borderWidth:'1px',
    cornerRadius:'11px', paddingTop:'10px', paddingBottom:'10px', paddingStart:'12px', paddingEnd:'12px', alignItems:'center', spacing:'sm', contents:[
      { type:'box', layout:'vertical', width:'7px', height:'7px', backgroundColor:'#c9820a', cornerRadius:'4px', flex:0, contents:[ { type:'filler' } ] },
      { type:'text', text:'บันทึกโดยไม่มีหลักฐาน', size:'sm', color:'#7a5a12', weight:'bold', gravity:'center' },
    ]};
}
function recentList(title: string, items: { label: string; amount: number }[], kind: 'out' | 'in') {
  const list = (items || []).slice(0, 3);
  const rows: any[] = [];
  list.forEach((r, i) => {
    rows.push({ type:'box', layout:'horizontal', paddingTop:'6px', paddingBottom:'6px', contents:[
      { type:'text', text:r.label, size:'xs', color:'#5c5c66', flex:1, gravity:'center', wrap:false },
      { type:'text', text:`${kind==='out'?'−':'+'}${money(r.amount)}`, size:'xs', color:kind==='out'?RED:GREEN, weight:'bold', align:'end', gravity:'center', flex:0 },
    ]});
    if (i < list.length - 1) rows.push({ type:'separator', color:'#f4f4f6' }); // hairline between rows
  });
  return { type:'box', layout:'vertical', margin:'14px', contents:[
    { type:'text', text:title, size:'xxs', color:'#c2c2c8', weight:'bold', margin:'sm' },
    ...rows,
  ]};
}
// ---- buttons ----
const act = (a: { data?: string; uri?: string }, label: string) =>
  a.uri ? { type:'uri', label, uri:a.uri } : { type:'postback', label, data:a.data!, displayText:label };
const primaryBtn = (label: string, a: { data?: string; uri?: string }, color = INK) =>
  ({ type:'button', style:'primary', color, height:'sm', action:act(a, label) });
const outlineBtn = (label: string, a: { data?: string; uri?: string }) =>
  ({ type:'box', layout:'vertical', flex:1, backgroundColor:'#FFFFFF', borderColor:INK, borderWidth:'1px', cornerRadius:'12px',
     contents:[{ type:'button', style:'link', color:INK, height:'sm', action:act(a, label) }] });
const ghostBtn = (label: string, a: { data?: string; uri?: string }) =>
  ({ type:'box', layout:'vertical', flex:1, backgroundColor:'#f1f1f3', cornerRadius:'12px',
     contents:[{ type:'button', style:'link', color:GRAY, height:'sm', action:act(a, label) }] });
// Filled primary as a BOX (not a raw LINE button) so its cornerRadius matches
// outlineBtn/ghostBtn exactly when sitting side-by-side in a btnRow.
const solidBtn = (label: string, a: { data?: string; uri?: string }, color = INK) =>
  ({ type:'box', layout:'vertical', flex:1, backgroundColor:color, cornerRadius:'12px',
     contents:[{ type:'button', style:'link', color:'#FFFFFF', height:'sm', action:act(a, label) }] });
const btnRow = (b: any[]) => ({ type:'box', layout:'horizontal', spacing:'lg', margin:'16px', contents:b });
const bodyBox = (contents: any[]) => ({ type:'box', layout:'vertical', paddingAll:'20px', contents });
// bubble(headerName, body, footer) — headerName picks the baked hero image.
const bubble = (headerName: string, b: any, f?: any) => {
  const o: any = { type:'bubble', size:'mega', body:b };
  if (AB) o.header = headerBox(headerName);
  if (f) o.footer = f;
  return o;
};
// Bottom "แก้ไขข้อมูล" button — always solid black per the design (cards 2/3/5).
// Opens the web app when LIFF_EDIT_URL is set; otherwise a postback that echoes
// the web-app link (never the old white outline fallback).
const editFooter = (url?: string, id?: string) => ({ type:'box', layout:'vertical', paddingStart:'20px', paddingEnd:'20px', paddingBottom:'18px',
  contents:[ solidBtn('แก้ไขข้อมูล', url ? { uri:url } : { data:`action=view&id=${id}` }) ] });

// ==================================================================== BUILDERS
// CARD 1 — ขอหลักฐาน (expense)
export function flexAskEvidence(e:{id:string, amount:number, category:string}) {
  return bubble('ask-evidence',
    bodyBox([
      captionRow(e.category || 'ค่าใช้จ่าย'),
      amount(e.amount, 'neutral'),
      SEP,
      { type:'text', margin:'lg', size:'xxs', wrap:true, contents:[
        { type:'span', text:'ส่งรูปใบเสร็จเพื่อบันทึกได้เลยครับ ', color:'#5c5c66' },
        { type:'span', text:'(ไม่ต้องกดปุ่ม)', color:MUTE },
      ]},
      btnRow([ outlineBtn('ไม่มีหลักฐาน', { data:`action=no_evidence&id=${e.id}` }), ghostBtn('ยกเลิก', { data:`action=retake&id=${e.id}` }) ]),
    ]));
}
// CARD 2 & 3 — บันทึกสำเร็จ (evidence flag switches the chip)
export function flexExpenseSuccess(e:{id:string, amount:number, vendor:string, category:string, payer:string, branch:string, balance:number, when:string, evidence?:string, recent?:{label:string,amount:number}[], editUrl?:string}) {
  return bubble('success-expense',
    bodyBox([
      captionRow(`${e.category || 'ค่าใช้จ่าย'} · ${e.branch}`),
      amount(e.amount, 'out'),
      evidenceChip(e.evidence !== 'none'),
      kv('วันที่บันทึก', e.when),
      SEP,
      balanceRow('ยอดคงเหลือ', String(e.balance)),
      recentList('3 รายการล่าสุด', e.recent || [], 'out'),
    ]),
    editFooter(e.editUrl, e.id));
}
// CARD 4 — ขอสลิปโอนเงิน (top-up)
export function flexTopupAskSlip(e:{id:string, amount:number}) {
  return bubble('ask-slip',
    bodyBox([
      captionRow('ยอดเติมเงิน'),
      amount(e.amount, 'neutral'),
      SEP,
      { type:'text', margin:'lg', size:'xxs', wrap:true, contents:[
        { type:'span', text:'ส่งรูปสลิปโอนเงินเพื่อยืนยันการเติม ', color:'#5c5c66' },
        { type:'span', text:'(ส่งรูปได้เลย ไม่ต้องกดปุ่ม)', color:MUTE },
      ]},
      btnRow([ outlineBtn('แนบภายหลัง', { data:`action=no_evidence&id=${e.id}` }), ghostBtn('ยกเลิก', { data:`action=retake&id=${e.id}` }) ]),
    ]));
}
// CARD 5 — เติมเงินสำเร็จ
export function flexTopup(e:{id?:string, amount:number, payer:string, branch:string, balance:number, round:string, method?:string, recent?:{label:string,amount:number}[], editUrl?:string}) {
  return bubble('success-topup',
    bodyBox([
      captionRow(`${e.method || 'โอนผ่านธนาคาร'} · ${e.payer}`),
      amount(e.amount, 'in'),
      kv('วันที่เติม', e.round),
      SEP,
      balanceRow('ยอดคงเหลือ', String(e.balance)),
      recentList('3 รายการเติมเงินล่าสุด', e.recent || [], 'in'),
    ]),
    editFooter(e.editUrl, e.id));
}
// CARD 6 — Sunlight: แจ้งค่าใช้จ่ายใหม่
export function flexSunlightExpense(e:{id:string, amount:number, category:string, who:string, branch:string, when:string, evidence?:string, branchBalance:number}) {
  return bubble('group-expense',
    bodyBox([
      captionRow(`${e.category || 'ค่าใช้จ่าย'} · บันทึกโดย ${e.who}`),
      amount(e.amount, 'out'),
      kv('สาขา', e.branch),
      kv('เวลา', e.when),
      evidenceChip(e.evidence !== 'none'),
      SEP,
      balanceRow('ยอดคงเหลือสาขา', String(e.branchBalance)),
      btnRow([ outlineBtn('ดูรายละเอียด', { data:`action=view&id=${e.id}` }) ]),
    ]));
}
// CARD 7 — Sunlight: แจ้งเติมเงินใหม่
export function flexSunlightTopup(e:{id:string, amount:number, who:string, branch:string, when:string, method?:string, branchBalance:number}) {
  return bubble('group-topup',
    bodyBox([
      captionRow(`${e.method || 'โอนผ่านธนาคาร'} · เติมโดย ${e.who}`),
      amount(e.amount, 'in'),
      kv('สาขา', e.branch),
      kv('เวลา', e.when),
      SEP,
      balanceRow('ยอดคงเหลือสาขา', String(e.branchBalance), GREEN),
      btnRow([ outlineBtn('ดูรายละเอียด', { data:`action=view&id=${e.id}` }) ]),
    ]));
}
// CARD 8 — Sunlight: แจ้งการแก้ไข (ก่อน→หลัง)
export function flexEdited(e:{id?:string, who:string, item?:string, field:string, before:string, after:string, when?:string, balance?:number, editUrl?:string}) {
  return bubble('group-edit',
    bodyBox([
      captionRow(`${e.item || 'รายการ'} · แก้ไขโดย ${e.who}`),
      { type:'box', layout:'horizontal', margin:'lg', spacing:'md', alignItems:'flex-end', contents:[
        { type:'box', layout:'vertical', flex:0, contents:[
          { type:'text', text:'เดิม', size:'xs', color:MUTE, weight:'bold' },
          { type:'text', text:e.before, size:'lg', color:MUTE, decoration:'line-through', weight:'bold' } ]},
        { type:'text', text:'→', size:'lg', color:RED, weight:'bold', flex:0, gravity:'bottom' },
        { type:'box', layout:'vertical', flex:0, contents:[
          { type:'text', text:'ใหม่', size:'xs', color:RED, weight:'bold' },
          { type:'text', text:e.after, size:'xxl', color:RED, weight:'bold' } ]},
      ]},
      SEP,
      kv('ช่องที่แก้', e.field),
      ...(e.when ? [kv('เวลาที่แก้', e.when)] : []),
      { type:'text', margin:'md', size:'xs', color:MUTE, text:'แก้ไขผ่านเว็บแอป' },
      btnRow([ e.editUrl ? outlineBtn('ดูรายการ', { uri:e.editUrl }) : outlineBtn('ดูรายการ', { data:`action=view&id=${e.id}` }) ]),
    ]));
}
// CARD 9 — อ่านรายการไม่ได้ (parse fail)
export function flexParseFail() {
  const ex = (t: string) => ({ type:'box', layout:'vertical', backgroundColor:'#FFFFFF', borderColor:'#e7e7ea', borderWidth:'1px',
    cornerRadius:'9px', paddingAll:'10px', margin:'sm', contents:[{ type:'text', text:t, size:'sm', color:VAL, weight:'bold' }] });
  return bubble('parse-fail',
    bodyBox([
      { type:'text', size:'sm', color:'#5c5c66', wrap:true, text:'น้อง Cammo อ่านข้อความนี้ไม่ออกครับ ลองพิมพ์ใหม่ตามรูปแบบด้านล่าง' },
      { type:'box', layout:'vertical', margin:'lg', backgroundColor:PANEL, cornerRadius:'14px', paddingAll:'14px', contents:[
        { type:'text', text:'ตัวอย่างการพิมพ์', size:'xxs', color:MUTE, weight:'bold' },
        ex('ค่าน้ำมัน 100'), ex('ค่าอาหาร 250'), ex('เติมเงิน 5000'),
      ]},
      { type:'text', margin:'md', size:'xs', color:MUTE, wrap:true, text:'หรือส่งรูปใบเสร็จมาได้เลย เดี๋ยวน้องอ่านให้ครับ' },
    ]));
}
// CARD 10 — ยอดคงเหลือ (balance check)
export function flexBalance(e:{branch:string, balance:number, monthIn:number, monthOut:number}) {
  const stat = (label: string, value: string, bg: string, color: string) => ({ type:'box', layout:'vertical', flex:1, backgroundColor:bg, cornerRadius:'12px', paddingAll:'12px', contents:[
    { type:'text', text:label, size:'xs', color:GRAY, weight:'bold' },
    { type:'text', text:value, size:'lg', color, weight:'bold', margin:'xs' } ]});
  return bubble('balance',
    bodyBox([
      captionRow(`กระเป๋าเงิน${e.branch}`),
      amount(e.balance, 'neutral'),
      { type:'box', layout:'horizontal', margin:'lg', spacing:'12px', contents:[
        stat('รายรับเดือนนี้', `+${money(e.monthIn)}`, '#eefaf3', GREEN),
        stat('รายจ่ายเดือนนี้', `−${money(e.monthOut)}`, '#fbeced', RED),
      ]},
      btnRow([ primaryBtn('ดูรายการทั้งหมด', { data:'action=list' }) ]),
    ]));
}
// CARD 11 — รายการหมดอายุ (basket expired)
export function flexPendingEvidence(e:{id:string, amount:number, item:string, minsLeft?:number}) {
  return bubble('expired',
    bodyBox([
      captionRow(e.item || 'รายการ'),
      amount(e.amount, 'neutral'),
      SEP,
      { type:'text', margin:'lg', size:'sm', color:'#5c5c66', wrap:true, text:'รายการนี้ค้างนานเกินไปจึงหมดอายุ พิมพ์ยอดพร้อมแนบบิลใหม่เพื่อบันทึกอีกครั้งครับ' },
      btnRow([ primaryBtn('บันทึกใหม่', { data:`action=retake&id=${e.id}` }) ]),
    ]));
}
// CARD 12 — ตรวจพบรูปซ้ำ
export function flexRejectedDuplicate(e:{id:string, amount:number, prevDate:string, prevBy:string, prevItem:string}) {
  return bubble('duplicate',
    bodyBox([
      captionRow('รูปนี้เคยถูกส่งแล้ว'),
      amount(e.amount, 'neutral'),
      kv('ส่งครั้งก่อน', `${e.prevDate}${e.prevBy && e.prevBy!=='-' ? ' · '+e.prevBy : ''}`),
      kv('รายการเดิม', e.prevItem),
      btnRow([ outlineBtn('ดูรายการเดิม', { data:`action=view&id=${e.id}` }), outlineBtn('ไม่ซ้ำ', { data:`action=second_installment&id=${e.id}` }) ]),
    ]));
}
// CARD 13 — สลิปน่าสงสัย (replaces generic flagged for slip cases)
export function flexSuspiciousSlip(e:{id:string, amount:number, item:string, reason:string, who?:string, balance?:number}) {
  return bubble('suspicious',
    bodyBox([
      captionRow(`${e.item || 'รายการ'}${e.who ? ' · '+e.who : ''}`),
      amount(e.amount, 'neutral'),
      { type:'box', layout:'horizontal', margin:'md', backgroundColor:'#fff8ec', borderColor:'#f4e2bd', borderWidth:'1px', cornerRadius:'11px', paddingAll:'11px', contents:[
        { type:'text', text:e.reason, size:'sm', color:'#7a5a12', weight:'bold', wrap:true } ]},
      ...(e.balance != null ? [SEP, balanceRow('ยอดคงเหลือ', String(e.balance))] : []),
      btnRow([ outlineBtn('ดูรายละเอียด', { data:`action=view&id=${e.id}` }), solidBtn('ยืนยันเอง', { data:`action=use_typed&id=${e.id}` }) ]),
    ]));
}
// Draft confirm (kept for compat; the new flow auto-saves so this is rarely shown)
export function flexDraftConfirm(e:{id:string, amount:number, vendor:string, category:string, ocrOk:boolean}) {
  return bubble('success-expense',
    bodyBox([
      captionRow(e.category || 'ค่าใช้จ่าย'),
      amount(e.amount, 'out'),
      kv('ร้าน', e.vendor),
      kv('OCR ตรวจยอด', e.ocrOk ? 'ตรงกับบิล' : 'ตรวจไม่ได้'),
      btnRow([ primaryBtn('ยืนยัน', { data:`action=confirm&id=${e.id}` }), ghostBtn('ยกเลิก', { data:`action=retake&id=${e.id}` }) ]),
    ]));
}
export function flexTopupConfirm(e:{id:string, amount:number}) {
  return bubble('ask-slip',
    bodyBox([
      captionRow('ตรวจยอดก่อนบันทึก'),
      amount(e.amount, 'in'),
      btnRow([ primaryBtn('ยืนยัน', { data:`action=confirm&id=${e.id}` }), ghostBtn('ยกเลิก', { data:`action=retake&id=${e.id}` }) ]),
    ]));
}
// Daily summary (admin cron)
export function flexDailySummary(e:{date:string, spentToday:number, totalBalance:number, toReview:number, items:{kind:'warn'|'bad', title:string, sub:string, amount:number}[]}) {
  const kpi = (l:string,v:string,c=INK)=>({type:'box',layout:'vertical',backgroundColor:PANEL,cornerRadius:'10px',paddingAll:'10px',flex:1,contents:[
    {type:'text',text:l,size:'xxs',color:GRAY,weight:'bold'},{type:'text',text:v,size:'md',weight:'bold',color:c,margin:'xs'}]});
  const sumrow=(it:any)=>({type:'box',layout:'horizontal',margin:'md',spacing:'sm',alignItems:'center',contents:[
    {type:'box',width:'8px',height:'8px',cornerRadius:'4px',backgroundColor:it.kind==='bad'?RED:'#c9820a',flex:0,contents:[{type:'filler'}]},
    {type:'text',text:it.title,size:'sm',color:VAL,flex:0,gravity:'center'},
    {type:'text',text:it.sub,size:'xs',color:GRAY,flex:1,gravity:'center'},
    {type:'text',text:baht(it.amount),size:'sm',weight:'bold',color:it.kind==='bad'?RED:'#c9820a',align:'end',gravity:'center'}]});
  return bubble('balance',
    bodyBox([
      captionRow(`${e.date} · 4 สาขา`),
      { type:'box', layout:'horizontal', margin:'lg', spacing:'sm', contents:[
        kpi('ใช้จ่ายวันนี้', baht(e.spentToday)), kpi('คงเหลือรวม', baht(e.totalBalance)), kpi('รอตรวจ', String(e.toReview), RED) ]},
      { type:'text', text:'รายการที่ต้องตรวจสอบ', size:'xs', color:GRAY, weight:'bold', margin:'lg' },
      ...e.items.map(sumrow),
    ]));
}

export const flexMessage = (altText: string, contents: any) => ({ type:'flex', altText, contents });
